# Generated by Django 4.1.7 on 2025-02-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_familia', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_largo_hilo', models.CharField(max_length=255)),
                ('largo_hilo', models.DecimalField(decimal_places=5, max_digits=12)),
                ('hilos_por_pulgada', models.IntegerField()),
                ('peso_producto', models.DecimalField(decimal_places=5, max_digits=12)),
                ('plano_ficha', models.FileField(blank=True, null=True, upload_to='planos_fichas/')),
                ('plano_ficha_path', models.CharField(blank=True, max_length=50, null=True)),
                ('calibra_ficha', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion_ficha', models.TextField(blank=True, null=True)),
                ('largo_cortar', models.DecimalField(decimal_places=5, max_digits=12)),
                ('observacion_mprima', models.TextField(blank=True, null=True)),
                ('estandar_ficha', models.CharField(blank=True, max_length=255, null=True)),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Utils.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='TerminacionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubfamiliaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_subfamilia', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('familia_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.familiaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=12, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('peso_unitario', models.DecimalField(decimal_places=5, max_digits=15)),
                ('armado', models.BooleanField(default=False)),
                ('familia_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.familiaproducto')),
                ('ficha_tecnica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='Product.fichatecnica')),
                ('subfamilia_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.subfamiliaproducto')),
                ('und_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Utils.measurementunit')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pieza', models.CharField(max_length=12, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('peso_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('familia_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.familiaproducto')),
                ('ficha_tecnica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieza', to='Product.fichatecnica')),
                ('subfamilia_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.subfamiliaproducto')),
                ('und_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Utils.measurementunit')),
            ],
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='terminacion_ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.terminacionficha'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Product.tipoproducto'),
        ),
    ]
