# Generated by Django 4.1.7 on 2024-12-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0001_initial'),
        ('JobManagement', '0003_alter_ordentrabajo_materia_prima_and_more'),
        ('Product', '0002_materiaprima_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Utils.materiaprima'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='und_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Utils.measurementunit'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='und_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Utils.measurementunit'),
        ),
        migrations.DeleteModel(
            name='MateriaPrima',
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
    ]
