# Generated by Django 4.1.7 on 2025-03-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0002_rename_motiov_estado_estadomaquina_motivo_estado'),
        ('JobManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='tipos_maquina_compatibles',
            field=models.ManyToManyField(related_name='procesos_compatibles', to='Machine.tipomaquina'),
        ),
    ]
