# Generated by Django 4.1.7 on 2025-02-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operator', '0001_initial'),
        ('JobManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrutaoperador',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_assignments', to='Operator.operador'),
        ),
        migrations.AddField(
            model_name='itemrutaoperador',
            name='programa_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_assignments', to='JobManagement.programaproduccion'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.proceso'),
        ),
        migrations.AddField(
            model_name='itemruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='JobManagement.rutaot'),
        ),
        migrations.AddField(
            model_name='disponibilidadmaquina',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina'),
        ),
        migrations.AddField(
            model_name='disponibilidadmaquina',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_maquina', to='JobManagement.programaproduccion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='disponibilidad_maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='JobManagement.disponibilidadmaquina'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='JobManagement.maquina'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='orden_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='JobManagement.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='JobManagement.programaproduccion'),
        ),
        migrations.AlterUniqueTogether(
            name='rutapieza',
            unique_together={('pieza', 'nro_etapa', 'proceso', 'maquina')},
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('producto', 'nro_etapa', 'proceso', 'maquina')},
        ),
        migrations.AlterUniqueTogether(
            name='programaordentrabajo',
            unique_together={('programa', 'orden_trabajo')},
        ),
        migrations.AlterUniqueTogether(
            name='proceso',
            unique_together={('empresa', 'codigo_proceso')},
        ),
        migrations.AlterUniqueTogether(
            name='maquina',
            unique_together={('empresa', 'codigo_maquina')},
        ),
        migrations.AlterUniqueTogether(
            name='itemrutaoperador',
            unique_together={('item_ruta', 'operador', 'programa_produccion')},
        ),
        migrations.AlterUniqueTogether(
            name='itemruta',
            unique_together={('ruta', 'item', 'maquina', 'proceso')},
        ),
    ]
