# Generated by Django 4.1.7 on 2024-12-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Operator', '0001_initial'),
        ('JobManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Programa Producción',
                'verbose_name_plural': 'Programas Producción',
            },
        ),
        migrations.RenameField(
            model_name='ordentrabajo',
            old_name='item_notaventa',
            new_name='item_nota_venta',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='nro_notaventa_ot',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='referencia_notaventa',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='und_medida_mprima',
        ),
        migrations.AddField(
            model_name='itemruta',
            name='terminado_sin_actualizar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='nro_nota_venta_ot',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='referencia_nota_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='unidad_medida_mprima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_of_medida_materia_prima', to='Product.measurementunit'),
        ),
        migrations.AlterField(
            model_name='empresaot',
            name='codigo_empresa',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='empresaot',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobManagement.empresaot'),
        ),
        migrations.CreateModel(
            name='DisponibilidadMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ocupado', models.BooleanField(default=False)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_maquina', to='JobManagement.programaproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupado', models.BooleanField(default=True)),
                ('disponibilidad_maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='JobManagement.disponibilidadmaquina')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='JobManagement.maquina')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='JobManagement.ordentrabajo')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='JobManagement.programaproduccion')),
            ],
            options={
                'verbose_name': 'Asignación de Recurso',
                'verbose_name_plural': 'Asignaciones de Recursos',
            },
        ),
        migrations.CreateModel(
            name='ProgramaOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.PositiveIntegerField()),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.ordentrabajo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion')),
            ],
            options={
                'unique_together': {('programa', 'orden_trabajo')},
            },
        ),
        migrations.CreateModel(
            name='ItemRutaOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('item_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_assignments', to='JobManagement.itemruta')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_assignments', to='Operator.operador')),
                ('programa_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_assignments', to='JobManagement.programaproduccion')),
            ],
            options={
                'unique_together': {('item_ruta', 'operador', 'programa_produccion')},
            },
        ),
    ]
