# Generated by Django 4.1.7 on 2025-03-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0003_asignacionoperador_updated_at'),
        ('JobManagement', '0002_proceso_tipos_maquina_compatibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervaloOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('MAQUINA', 'Maquina'), ('OPERADOR', 'Operador')], max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.operador')),
            ],
        ),
        migrations.CreateModel(
            name='IntervaloMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('MAQUINA', 'Maquina'), ('OPERADOR', 'Operador')], max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina')),
            ],
        ),
        migrations.AddConstraint(
            model_name='intervalooperador',
            constraint=models.UniqueConstraint(fields=('operador', 'fecha_inicio'), name='unique_operador_intervalo'),
        ),
        migrations.AddConstraint(
            model_name='intervalomaquina',
            constraint=models.UniqueConstraint(fields=('maquina', 'fecha_inicio'), name='unique_maquina_intervalo'),
        ),
    ]
