# Generated by Django 4.1.7 on 2025-02-11 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOperatividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OP', 'Operativa'), ('MN', 'En Mantención'), ('IN', 'Inoperativa')], max_length=2)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('PR', 'Preventivo'), ('CR', 'Correctivo'), ('PD', 'Predictivo')], max_length=2)),
                ('prioridad', models.CharField(choices=[('AL', 'Alta'), ('MD', 'Media'), ('BJ', 'Baja')], default='MD', max_length=2)),
                ('estado', models.CharField(choices=[('PG', 'Programado'), ('EP', 'En Proceso'), ('CM', 'Completado'), ('CN', 'Cancelado')], default='PG', max_length=2)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_estimada', models.DurationField(help_text='Duración estimada del mantenimiento')),
                ('descripcion', models.TextField(help_text='Descripción del mantenimiento')),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, help_text='Resultados y observaciones post-mantenimiento', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='JobManagement.maquina')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Máquina',
                'verbose_name_plural': 'Mantenimientos de Máquinas',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo_cambio', models.TextField()),
                ('estado_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_anterior', to='Machine.estadooperatividad')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_nuevo', to='Machine.estadooperatividad')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='JobManagement.maquina')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiov_estado', models.TextField(blank=True, null=True)),
                ('fecha_ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('disponible', models.BooleanField(default=True)),
                ('capacidad_maxima', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_operatividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Machine.estadooperatividad')),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='JobManagement.maquina')),
                ('tipo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Machine.tipomaquina')),
            ],
        ),
    ]
