# Generated by Django 4.1.7 on 2025-03-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadomaquina',
            old_name='motiov_estado',
            new_name='motivo_estado',
        ),
    ]
