# Generated by Django 4.1.7 on 2025-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0002_rename_motiov_estado_estadomaquina_motivo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadomaquina',
            name='tipo_maquina',
        ),
        migrations.AddField(
            model_name='estadomaquina',
            name='tipos_maquina',
            field=models.ManyToManyField(related_name='maquinas', to='Machine.tipomaquina'),
        ),
        migrations.AddField(
            model_name='tipomaquina',
            name='accion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
