# Generated by Django 4.1.7 on 2025-03-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0003_remove_estadomaquina_tipo_maquina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomaquina',
            options={'verbose_name': 'Tipo de Máquina', 'verbose_name_plural': 'Tipos de Máquina'},
        ),
        migrations.RemoveField(
            model_name='tipomaquina',
            name='accion',
        ),
    ]
