# Generated by Django 4.1.7 on 2025-02-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JobManagement.empresaot')),
            ],
        ),
        migrations.CreateModel(
            name='OperadorMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_habilitacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.maquina')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.operador')),
            ],
            options={
                'unique_together': {('operador', 'maquina')},
            },
        ),
        migrations.AddField(
            model_name='operador',
            name='maquinas_habilitadas',
            field=models.ManyToManyField(related_name='operadores', through='Operator.OperadorMaquina', to='JobManagement.maquina'),
        ),
        migrations.CreateModel(
            name='AsignacionOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.itemruta')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Operator.operador')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobManagement.programaproduccion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='asignacionoperador',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='check_fecha_fin_mayor_inicio'),
        ),
    ]
