# Generated by Django 4.1.7 on 2025-02-17 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0002_initial'),
        ('Operator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadoperador',
            name='proceso_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobManagement.proceso'),
        ),
        migrations.AddField(
            model_name='disponibilidadoperador',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Turno Mañana'), ('TARDE', 'Turno Tarde')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$')]),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadoperador',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='fecha_fin_posterior_inicio'),
        ),
    ]
