# Generated by Django 4.1.7 on 2024-12-26 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0002_programaproduccion_and_more'),
        ('Operator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operador',
            old_name='disponible',
            new_name='activo',
        ),
        migrations.AddField(
            model_name='asignacionoperador',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_operadores', to='JobManagement.programaproduccion'),
        ),
        migrations.CreateModel(
            name='DisponibilidadOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ocupado', models.BooleanField(default=False)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operator.operador')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_operadores', to='JobManagement.programaproduccion')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Operador',
                'verbose_name_plural': 'Disponibilidades de Operadores',
            },
        ),
    ]
