# Generated by Django 4.1.7 on 2025-03-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobManagement', '0002_proceso_tipos_maquina_compatibles'),
        ('Operator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operadormaquina',
            options={'verbose_name': 'Habilitación de máquina', 'verbose_name_plural': 'Habilitaciónes de máquinas'},
        ),
        migrations.AlterField(
            model_name='operador',
            name='maquinas_habilitadas',
            field=models.ManyToManyField(related_name='operadores_habilitados', through='Operator.OperadorMaquina', to='JobManagement.maquina'),
        ),
    ]
