# Generated by Django 4.1.7 on 2025-03-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operator', '0002_alter_operadormaquina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionoperador',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
