# Generated by Django 4.1.7 on 2025-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('vip', models.BooleanField(default=False)),
                ('apodo', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo_cliente'], name='Client_clie_codigo__0898e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['apodo'], name='Client_clie_apodo_11f66e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('codigo_cliente', 'nombre', 'apodo')},
        ),
    ]
